import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract final class AppTheme {
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.dellGenoa,
    subThemesData: const FlexSubThemesData(
      inputDecoratorIsFilled: true,
      alignedDropdown: true,
      tooltipRadius: 4,
      tooltipSchemeColor: SchemeColor.inverseSurface,
      tooltipOpacity: 0.9,
      snackBarElevation: 6,
      snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    keyColors: const FlexKeyColors(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    fontFamily: 'Kenyan Coffee Rg',
  );

  static ThemeData dark = FlexThemeData.dark(
    scheme: FlexScheme.deepOrangeM3,
    subThemesData: const FlexSubThemesData(
      blendOnColors: true,
      inputDecoratorIsFilled: true,
      alignedDropdown: true,
      tooltipRadius: 4,
      tooltipSchemeColor: SchemeColor.inverseSurface,
      tooltipOpacity: 0.9,
      snackBarElevation: 6,
      snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    keyColors: const FlexKeyColors(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    fontFamily: 'Kenyan Coffee Rg',
  );
}

/// Light [ColorScheme] made with FlexColorScheme v8.1.1.
/// Requires Flutter 3.22.0 or later.
const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF8F4B39),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDBD1),
  onPrimaryContainer: Color(0xFF3A0A01),
  primaryFixed: Color(0xFFFFDBD1),
  primaryFixedDim: Color(0xFFFFB5A1),
  onPrimaryFixed: Color(0xFF3A0A01),
  onPrimaryFixedVariant: Color(0xFF723524),
  secondary: Color(0xFF77574E),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFDBD1),
  onSecondaryContainer: Color(0xFF2C150F),
  secondaryFixed: Color(0xFFFFDBD1),
  secondaryFixedDim: Color(0xFFE7BDB2),
  onSecondaryFixed: Color(0xFF2C150F),
  onSecondaryFixedVariant: Color(0xFF5D4038),
  tertiary: Color(0xFF6C5D2E),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF6E1A6),
  onTertiaryContainer: Color(0xFF231B00),
  tertiaryFixed: Color(0xFFF6E1A6),
  tertiaryFixedDim: Color(0xFFD9C58D),
  onTertiaryFixed: Color(0xFF231B00),
  onTertiaryFixedVariant: Color(0xFF534619),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFFF8F6),
  onSurface: Color(0xFF231917),
  surfaceDim: Color(0xFFE8D6D2),
  surfaceBright: Color(0xFFFFF8F6),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFFFF1ED),
  surfaceContainer: Color(0xFFFCEAE5),
  surfaceContainerHigh: Color(0xFFF7E4E0),
  surfaceContainerHighest: Color(0xFFF1DFDA),
  onSurfaceVariant: Color(0xFF53433F),
  outline: Color(0xFF85736E),
  outlineVariant: Color(0xFFD8C2BC),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF392E2B),
  onInverseSurface: Color(0xFFFFEDE9),
  inversePrimary: Color(0xFFFFB5A1),
  surfaceTint: Color(0xFF8F4B39),
);

/// Dark [ColorScheme] made with FlexColorScheme v8.1.1.
/// Requires Flutter 3.22.0 or later.
const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB5A1),
  onPrimary: Color(0xFF561F10),
  primaryContainer: Color(0xFF723524),
  onPrimaryContainer: Color(0xFFFFDBD1),
  primaryFixed: Color(0xFFFFDBD1),
  primaryFixedDim: Color(0xFFFFB5A1),
  onPrimaryFixed: Color(0xFF3A0A01),
  onPrimaryFixedVariant: Color(0xFF723524),
  secondary: Color(0xFFE7BDB2),
  onSecondary: Color(0xFF442A23),
  secondaryContainer: Color(0xFF5D4038),
  onSecondaryContainer: Color(0xFFFFDBD1),
  secondaryFixed: Color(0xFFFFDBD1),
  secondaryFixedDim: Color(0xFFE7BDB2),
  onSecondaryFixed: Color(0xFF2C150F),
  onSecondaryFixedVariant: Color(0xFF5D4038),
  tertiary: Color(0xFFD9C58D),
  onTertiary: Color(0xFF3B2F05),
  tertiaryContainer: Color(0xFF534619),
  onTertiaryContainer: Color(0xFFF6E1A6),
  tertiaryFixed: Color(0xFFF6E1A6),
  tertiaryFixedDim: Color(0xFFD9C58D),
  onTertiaryFixed: Color(0xFF231B00),
  onTertiaryFixedVariant: Color(0xFF534619),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF1A110F),
  onSurface: Color(0xFFF1DFDA),
  surfaceDim: Color(0xFF1A110F),
  surfaceBright: Color(0xFF423734),
  surfaceContainerLowest: Color(0xFF140C0A),
  surfaceContainerLow: Color(0xFF231917),
  surfaceContainer: Color(0xFF271D1B),
  surfaceContainerHigh: Color(0xFF322825),
  surfaceContainerHighest: Color(0xFF3D3230),
  onSurfaceVariant: Color(0xFFD8C2BC),
  outline: Color(0xFFA08C88),
  outlineVariant: Color(0xFF53433F),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFFF1DFDA),
  onInverseSurface: Color(0xFF392E2B),
  inversePrimary: Color(0xFF8F4B39),
  surfaceTint: Color(0xFFFFB5A1),
);
